services:
  mysql:
    image: docker.io/mysql:9.6
    container_name: tournoi-baby-foot-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tournoi_baby_foot
      MYSQL_USER: tournoi
      MYSQL_PASSWORD: ionruot
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
