### Auth
POST localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "nimda"
}

> {% client.global.set("auth_token", response.body.access_token); %}

### Get tournois
GET localhost:3000/api/tournois/1
Authorization: Bearer {{auth_token}}

### Get tournois
GET localhost:3000/api/tournois

